# Keep the examples buildable with older installed packages until they acquire
# the tendon API. Probe capabilities instead of changing the release version.
include(CheckCXXSourceCompiles)
include(CMakePushCheckState)
function(add_tendon_examples)
    set(CMAKE_CXX_STANDARD 20)
    set(CMAKE_CXX_STANDARD_REQUIRED ON)
    cmake_push_check_state(RESET)
    set(CMAKE_REQUIRED_LIBRARIES raisim::raisim)
    unset(RAISIM_EXAMPLES_HAVE_TENDONS CACHE)
    check_cxx_source_compiles("#include <raisim/World.hpp>
      int main() { raisim::World world; raisim::Tendon::Properties p;
        return int(world.getTendons().size()); }" RAISIM_EXAMPLES_HAVE_TENDONS)
    if(NOT RAISIM_EXAMPLES_HAVE_TENDONS)
        message(STATUS "Skipping tendon examples: install a RaiSim package with tendon support.")
        cmake_pop_check_state()
        return()
    endif()
    foreach(scene elastic pulleys coupling)
        create_executable(tendon_${scene} src/server/dynamics/tendon_${scene}.cpp)
        target_compile_features(tendon_${scene} PRIVATE cxx_std_20)
    endforeach()
    set(CMAKE_REQUIRED_LIBRARIES rayrai)
    unset(RAISIM_EXAMPLES_HAVE_TENDON_VISUALS CACHE)
    check_cxx_source_compiles("#include <rayrai/RayraiWindow.hpp>
      void probe(const raisin::RayraiWindow& viewer) { viewer.getTendonVisual(\"probe\"); }
      int main() { return 0; }" RAISIM_EXAMPLES_HAVE_TENDON_VISUALS)
    if(RAISIM_EXAMPLES_HAVE_TENDON_VISUALS)
        create_rayrai_executable(rayrai_tendons src/rayrai/dynamics/rayrai_tendons.cpp)
        target_compile_features(rayrai_tendons PRIVATE cxx_std_20)
    else()
        message(STATUS "Skipping rayrai_tendons: install Rayrai with automatic tendon rendering.")
    endif()
    cmake_pop_check_state()
endfunction()
add_tendon_examples()
