# Keep the examples buildable with older installed packages until they acquire
# the tendon API. Probe capabilities instead of changing the release version.
include(CheckCXXSourceCompiles)
include(CMakePushCheckState)
function(add_tendon_examples)
    set(CMAKE_CXX_STANDARD 20)
    set(CMAKE_CXX_STANDARD_REQUIRED ON)
    cmake_push_check_state(RESET)
    set(CMAKE_REQUIRED_LIBRARIES raisim::raisim)
    unset(RAISIM_EXAMPLES_HAVE_TENDONS CACHE)
    check_cxx_source_compiles("#include <raisim/World.hpp>
      int main() { raisim::World world; raisim::Tendon::Properties p;
        return int(world.getTendons().size()); }" RAISIM_EXAMPLES_HAVE_TENDONS)
    if(NOT RAISIM_EXAMPLES_HAVE_TENDONS)
        message(STATUS "Skipping tendon examples: install a RaiSim package with tendon support.")
        cmake_pop_check_state()
        return()
    endif()
    foreach(scene elastic pulleys coupling)
        create_executable(tendon_${scene} src/server/dynamics/tendon_${scene}.cpp)
        target_compile_features(tendon_${scene} PRIVATE cxx_std_20)
    endforeach()
    set(CMAKE_REQUIRED_LIBRARIES rayrai)
    unset(RAISIM_EXAMPLES_HAVE_TENDON_VISUALS CACHE)
    check_cxx_source_compiles("#include <rayrai/RayraiWindow.hpp>
      void probe(const raisin::RayraiWindow& viewer) { viewer.getTendonVisual(\"probe\"); }
      int main() { return 0; }" RAISIM_EXAMPLES_HAVE_TENDON_VISUALS)
    if(RAISIM_EXAMPLES_HAVE_TENDON_VISUALS)
        create_rayrai_executable(rayrai_tendons src/rayrai/dynamics/rayrai_tendons.cpp)
        target_compile_features(rayrai_tendons PRIVATE cxx_std_20)
    else()
        message(STATUS "Skipping rayrai_tendons: install Rayrai with automatic tendon rendering.")
    endif()
    cmake_pop_check_state()
endfunction()
add_tendon_examples()

option(RAISIM_TENDON_EXAMPLE_TESTS "Register tendon example CTest checks" OFF)
set(RAISIM_EXAMPLE_ACTIVATION_KEY "" CACHE FILEPATH "Optional RaiSim license path for example tests")
if(RAISIM_TENDON_EXAMPLE_TESTS AND TARGET tendon_elastic)
    enable_testing()
    set(tendon_test_key)
    if(RAISIM_EXAMPLE_ACTIVATION_KEY)
        list(APPEND tendon_test_key --activation-key "${RAISIM_EXAMPLE_ACTIVATION_KEY}")
    endif()
    create_executable(tendon_example_export_check tests/test_tendon_export.cpp)
    target_compile_features(tendon_example_export_check PRIVATE cxx_std_20)
    add_test(NAME tendon_example_export_roundtrip COMMAND tendon_example_export_check ${tendon_test_key})
    set_tests_properties(tendon_example_export_roundtrip PROPERTIES TIMEOUT 30)
    create_executable(tendon_example_coupling_check tests/test_tendon_coupling.cpp)
    target_compile_features(tendon_example_coupling_check PRIVATE cxx_std_20)
    add_test(NAME tendon_example_coupling_routes COMMAND tendon_example_coupling_check ${tendon_test_key})
    set_tests_properties(tendon_example_coupling_routes PROPERTIES TIMEOUT 30)
    foreach(scene elastic pulleys coupling)
        add_test(NAME tendon_example_${scene} COMMAND tendon_${scene} --headless --steps 6000 ${tendon_test_key})
        set_tests_properties(tendon_example_${scene} PROPERTIES TIMEOUT 30)
    endforeach()
    if(TARGET rayrai_tendons)
        add_test(NAME tendon_example_all_headless COMMAND rayrai_tendons --headless --steps 6000 ${tendon_test_key})
        add_test(NAME tendon_example_rayrai COMMAND rayrai_tendons --hidden --frames 8 ${tendon_test_key})
        set_tests_properties(tendon_example_rayrai PROPERTIES TIMEOUT 90 LABELS "gpu" SKIP_RETURN_CODE 77)
        add_test(NAME tendon_example_coupling_rayrai COMMAND rayrai_tendons --scene coupling --hidden --frames 8 ${tendon_test_key})
        set_tests_properties(tendon_example_coupling_rayrai PROPERTIES TIMEOUT 90 LABELS "gpu" SKIP_RETURN_CODE 77)
        create_rayrai_executable(tendon_example_coupling_tcp_check tests/test_tendon_coupling_tcp.cpp)
        target_compile_features(tendon_example_coupling_tcp_check PRIVATE cxx_std_20)
        add_test(NAME tendon_example_coupling_tcp COMMAND tendon_example_coupling_tcp_check ${tendon_test_key})
        set_tests_properties(tendon_example_coupling_tcp PROPERTIES TIMEOUT 90 LABELS "gpu" SKIP_RETURN_CODE 77)
    endif()
    find_package(Python3 COMPONENTS Interpreter QUIET)
    if(Python3_Interpreter_FOUND)
        add_test(NAME tendon_example_cli_and_export COMMAND "${Python3_EXECUTABLE}"
            "${CMAKE_CURRENT_SOURCE_DIR}/tests/test_tendon_examples.py"
            "$<TARGET_FILE:tendon_elastic>" "$<TARGET_FILE:tendon_pulleys>" "$<TARGET_FILE:tendon_coupling>"
            ${tendon_test_key})
        set_tests_properties(tendon_example_cli_and_export PROPERTIES TIMEOUT 45)
    endif()
endif()
